[package]
name = "aes"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "pyaes"
#crate-type = ["cdylib"]
#path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.24.2", features = ["extension-module"] }
rand = "0.9.1"
